### ISSUE TITLE
fail to run example PythonSlave FMU in Linux

### ISSUE THREAD

**Issue by alfoa** [NTNU-IHB/PythonFMU#115]
Hi. 
I am trying to use this tool for the deployment of CO-SIM (hopefully ME in the future?) python models.
When I try to export the FMU using the example in the README (PythonSlave), the export is successful but when I use it  (in Linux Centos 7) with an external tool (FMPy) I get the following error:

```
>>> fmu = FMU2Slave(guid=model_description.guid,unzipDirectory=unzipdir,modelIdentifier=model_description.coSimulation.modelIdentifier,instanceName='instance1')
Traceback (most recent call last):
  File "/home/alfoa/.conda/envs/raven_libraries/lib/python3.7/site-packages/fmpy/fmi1.py", line 141, in __init__
    self.dll = cdll.LoadLibrary(libraryPath)
  File "/home/alfoa/.conda/envs/raven_libraries/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/home/alfoa/.conda/envs/raven_libraries/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alfoa/.conda/envs/raven_libraries/lib/python3.7/site-packages/fmpy/fmi2.py", line 519, in __init__
    super(FMU2Slave, self).__init__(**kwargs)
  File "/home/alfoa/.conda/envs/raven_libraries/lib/python3.7/site-packages/fmpy/fmi2.py", line 85, in __init__
    super(_FMU2, self).__init__(**kwargs)
  File "/home/alfoa/.conda/envs/raven_libraries/lib/python3.7/site-packages/fmpy/fmi1.py", line 143, in __init__
    raise Exception("Failed to load shared library %s. %s" % (libraryPath, e))
Exception: Failed to load shared library /tmp/tmp1irk0351/binaries/linux64/PythonSlave.so. libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```

I am using conda for the installation of FMPy and Pip for PythonFMU. 

Python version: Python 3.7.9

**Comment by markaren** [comment]
> hopefully ME in the future

I have no plans to support ME

> /home/alfoa/.conda/envs/raven_libraries/lib/python3.7/site-packages/fmpy/fmi1.py

No idea why it think it is FMI1. The modelDescription.xml looks ok, right?

> OSError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory

Don't know why it looks for Python 3.9. I have no experience with Centos 7. The .so is built on and runs on Ubuntu. Can't answer for other unix flavors. A solution could be to build the .so manually and replace the one in the FMU.

**Comment by Robotics010** [comment]
I've got the same error on Ubuntu 18.04:
```
Failed to load shared library /tmp/tmpezm4wk87/binaries/linux64/PythonSlave.so. libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```
And I've got it resolved after installing `libpython3.9.so` and adding to LD path as follows:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu
```
where `/usr/lib/x86_64-linux-gnu` is the path to the so library. In my case it has such pylibs:
```
ls /usr/lib/x86_64-linux-gnu/libpython*
/usr/lib/x86_64-linux-gnu/libpython2.7.a       /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1
/usr/lib/x86_64-linux-gnu/libpython2.7.so      /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1    /usr/lib/x86_64-linux-gnu/libpython3.9.a
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0  /usr/lib/x86_64-linux-gnu/libpython3.9.so
/usr/lib/x86_64-linux-gnu/libpython3.6m.a      /usr/lib/x86_64-linux-gnu/libpython3.9.so.1
/usr/lib/x86_64-linux-gnu/libpython3.6m.so     /usr/lib/x86_64-linux-gnu/libpython3.9.so.1.0
```
