### ISSUE TITLE
CSV to FMU?

### ISSUE THREAD

**Issue by kosmylo** [NTNU-IHB/PythonFMU#132]
I have used the tool successfully to turn python code to FMU, but I noticed in the description that it can be used to convert CSV files to FMU. How something like that could be possible?

**Comment by markaren** [comment]
Yeah, so this is a feature with basically where basically no documentation exists.

However, if you have a CSV file with that follows the structure of https://github.com/NTNU-IHB/PythonFMU/blob/master/pythonfmu/tests/data/csvdemo.csv, then it should work. For real values parameters, interpolation will be used.

**Comment by kosmylo** [comment]
Awesome! Thanks!

**Comment by kosmylo** [comment]
I managed to export the FMU from the CSV file, but when I am trying to load it through pyfmi I am getting the following error:

```
Traceback (most recent call last):

  File "<ipython-input-4-d6a3aa429faa>", line 1, in <module>
    sub_system3 = load_fmu(r"C:\Users\kosmy\Test_Pandapower_FMU\Pv_prof.fmu")

  File "src\pyfmi\fmi.pyx", line 8707, in pyfmi.fmi.load_fmu

  File "src\pyfmi\fmi.pyx", line 6998, in pyfmi.fmi.FMUModelCS2.__init__

FMUException: Models that need an execution tool are not supported
```

Any idea of why this is happening?

I need to mention that the FMU passes the validation of the online tool FMU Check.

**Comment by kosmylo** [comment]
I have a CSV of the following form:

time, power
0,0.00384
1,0.003733
2,0.00318
...
95,0.004295

And I used the command: `CsvFmuBuilder.build_FMU(csv_file, dest)` to turn the CSV into FMU with the intention of simulating as FMU with `fmpy` and get as a result the values of power at each timestep.

However, when I am trying to simulate it with the command `simulate_fmu(fmu, start_time = 0.0, stop_time = 96.0, step_size = 1.0) ` I am getting an array of (961,) with the elements:
0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1
1.1

Any idea of why is this happening?

**Comment by markaren** [comment]
Mind sharing the FMU?

**Comment by kosmylo** [comment]
Yes, sure.

[FMU.zip](https://github.com/NTNU-IHB/PythonFMU/files/6917983/FMU.zip)

**Comment by markaren** [comment]
Also tried with a custom software running with 1s intervals. No issues.

```
time, stepNumber, num_rows [INT OUTPUT], power [REAL OUTPUT], end_time [REAL OUTPUT], interpolate [BOOLEAN PARAMETER]
0.00000000, 0, 96, 0.0038403299999999994, 95.0, true
1.00000000, 1, 96, 0.003732525, 95.0, true
2.00000000, 2, 96, 0.0031795999995, 95.0, true
3.00000000, 3, 96, 0.003027375, 95.0, true
4.00000000, 4, 96, 0.00313746, 95.0, true
5.00000000, 5, 96, 0.002979, 95.0, true
6.00000000, 6, 96, 0.00283575, 95.0, true
7.00000000, 7, 96, 0.0028038599999999996, 95.0, true
8.00000000, 8, 96, 0.0028051000005000003, 95.0, true
9.00000000, 9, 96, 0.0027548625, 95.0, true
10.00000000, 10, 96, 0.0027157199999999996, 95.0, true
11.00000000, 11, 96, 0.0027835000004999997, 95.0, true
12.00000000, 12, 96, 0.002734233333, 95.0, true
13.00000000, 13, 96, 0.002884425, 95.0, true
14.00000000, 14, 96, 0.0029904, 95.0, true
15.00000000, 15, 96, 0.0027343124999999998, 95.0, true
16.00000000, 16, 96, 0.00279819, 95.0, true
17.00000000, 17, 96, 0.0028813199999999997, 95.0, true
18.00000000, 18, 96, 0.00304683, 95.0, true
19.00000000, 19, 96, 0.0034204500000000002, 95.0, true
20.00000000, 20, 96, 0.0036694999995, 95.0, true
21.00000000, 21, 96, 0.0036131249999999996, 95.0, true
22.00000000, 22, 96, 0.00393735, 95.0, true
23.00000000, 23, 96, 0.0049771999995, 95.0, true
24.00000000, 24, 96, 0.00654525, 95.0, true
25.00000000, 25, 96, 0.007523175, 95.0, true
26.00000000, 26, 96, 0.007891800000000001, 95.0, true
27.00000000, 27, 96, 0.00805725, 95.0, true
28.00000000, 28, 96, 0.009218774999999998, 95.0, true
29.00000000, 29, 96, 0.0094657875, 95.0, true
30.00000000, 30, 96, 0.009133912499999999, 95.0, true
31.00000000, 31, 96, 0.0091179, 95.0, true
32.00000000, 32, 96, 0.009370725, 95.0, true
33.00000000, 33, 96, 0.01005468, 95.0, true
34.00000000, 34, 96, 0.010364100000000001, 95.0, true
35.00000000, 35, 96, 0.0096072, 95.0, true
36.00000000, 36, 96, 0.009588, 95.0, true
37.00000000, 37, 96, 0.009550425, 95.0, true
38.00000000, 38, 96, 0.009791024999999998, 95.0, true
39.00000000, 39, 96, 0.00985305, 95.0, true
40.00000000, 40, 96, 0.010171679999999999, 95.0, true
41.00000000, 41, 96, 0.0097313625, 95.0, true
42.00000000, 42, 96, 0.009173625, 95.0, true
43.00000000, 43, 96, 0.009437250000000001, 95.0, true
44.00000000, 44, 96, 0.00906855, 95.0, true
45.00000000, 45, 96, 0.0092107999995, 95.0, true
46.00000000, 46, 96, 0.010544475, 95.0, true
47.00000000, 47, 96, 0.010896929999999999, 95.0, true
48.00000000, 48, 96, 0.010906500000000001, 95.0, true
49.00000000, 49, 96, 0.010959, 95.0, true
50.00000000, 50, 96, 0.01078005, 95.0, true
51.00000000, 51, 96, 0.0104150500005, 95.0, true
52.00000000, 52, 96, 0.009750400000499999, 95.0, true
53.00000000, 53, 96, 0.00949296, 95.0, true
54.00000000, 54, 96, 0.0085640500005, 95.0, true
55.00000000, 55, 96, 0.0084739125, 95.0, true
56.00000000, 56, 96, 0.008481225, 95.0, true
57.00000000, 57, 96, 0.0078580928565, 95.0, true
58.00000000, 58, 96, 0.007388550000000001, 95.0, true
59.00000000, 59, 96, 0.0074004, 95.0, true
60.00000000, 60, 96, 0.00742347, 95.0, true
61.00000000, 61, 96, 0.007227750000000001, 95.0, true
62.00000000, 62, 96, 0.00694575, 95.0, true
63.00000000, 63, 96, 0.006738900000000001, 95.0, true
64.00000000, 64, 96, 0.0068737500000000005, 95.0, true
65.00000000, 65, 96, 0.0076253500005, 95.0, true
66.00000000, 66, 96, 0.00776295, 95.0, true
67.00000000, 67, 96, 0.0086238499995, 95.0, true
68.00000000, 68, 96, 0.00947085, 95.0, true
69.00000000, 69, 96, 0.010427474999999999, 95.0, true
70.00000000, 70, 96, 0.0108558, 95.0, true
71.00000000, 71, 96, 0.011647274999999999, 95.0, true
72.00000000, 72, 96, 0.012194100000000001, 95.0, true
73.00000000, 73, 96, 0.012893678571, 95.0, true
74.00000000, 74, 96, 0.0130329, 95.0, true
75.00000000, 75, 96, 0.013536389999999999, 95.0, true
76.00000000, 76, 96, 0.013721662499999999, 95.0, true
77.00000000, 77, 96, 0.013567687499999998, 95.0, true
78.00000000, 78, 96, 0.01326606, 95.0, true
79.00000000, 79, 96, 0.0124459999995, 95.0, true
80.00000000, 80, 96, 0.0123139928565, 95.0, true
81.00000000, 81, 96, 0.0119358499995, 95.0, true
82.00000000, 82, 96, 0.011080979999999999, 95.0, true
83.00000000, 83, 96, 0.010501350000000001, 95.0, true
84.00000000, 84, 96, 0.010335649999499999, 95.0, true
85.00000000, 85, 96, 0.01016595, 95.0, true
86.00000000, 86, 96, 0.009693150000000001, 95.0, true
87.00000000, 87, 96, 0.00920706, 95.0, true
88.00000000, 88, 96, 0.008104900000500001, 95.0, true
89.00000000, 89, 96, 0.0074855571434999995, 95.0, true
90.00000000, 90, 96, 0.007038128570999999, 95.0, true
91.00000000, 91, 96, 0.006534900000000001, 95.0, true
92.00000000, 92, 96, 0.00616305, 95.0, true
93.00000000, 93, 96, 0.005170724999999999, 95.0, true
94.00000000, 94, 96, 0.004560389999999999, 95.0, true
```
