### ISSUE TITLE
__init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by FlorianKarg** [NTNU-IHB/PythonFMU#64]
I can't create a FMU. 
I'm trying to run `pythonfmu-builder -f pythonslave.py pythonfmu` and am getting the following error:

Traceback (most recent call last): 
File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_ma n return _run_code(code, main_globals, None, 
File "c:\program files\python38\lib\runpy.py", line 86, in _run_code exec(code, run_globals)
File "C:\Users\karg\AppData\Roaming\Python\Python38\Scripts\pythonfmu-builder exe\__main__.py", line 7, in <module> 
File "C:\Users\karg\AppData\Roaming\Python\Python38\site-packages\pythonfmu\b ilder.py", line 234, in main FmuBuilder.build_FMU(**options) 
File "C:\Users\karg\AppData\Roaming\Python\Python38\site-packages\pythonfmu\b ilder.py", line 120, in build_FMU model_identifier, xml = ModelDescriptionFetcher.get_model_description( File "C:\Users\karg\AppData\Roaming\Python\Python38\site-packages\pythonfmu\b ilder.py", line 53, in get_model_description instance = getattr(fmu_interface, class_name)("dummyInstance") 
**TypeError: __init__() takes 1 positional argument but 2 were given**

**Comment by markaren** [comment]
Version 0.3.0 takes a single `str` as argument, while master takes a `**kwargs`. Wait for 0.4.0 or change your `ctor` to take a single `str`argument and pass it to super.

```python
def __init__(self, instance_name):
        super().__init__(instance_name)
```

**Comment by sentient-jgallegocalderon** [comment]
Hi -- I just came across this code today and I am having the same problem. Can you please clarify where to make the change you propose above? Thank you.

**Comment by markaren** [comment]
v0.4.0 (soon to be released - get/set state, works with FMPy ++)
```python
class PythonSlave(Fmi2Slave):

    author = "John Doe"
    modelName = "PythonSlave"  # OPTIONAL in v.0.4.0
    description = "A simple description"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
```

v0.3.0
```python
class PythonSlave(Fmi2Slave):

    author = "John Doe"
    modelName = "PythonSlave"  # REQUIRED in v0.3.0
    description = "A simple description"

    def __init__(self, instance_name):
        super().__init__(instance_name)
```

**Comment by fcollonval** [comment]
@FlorianKarg @sentient-jgallegocalderon 

v0.4.0 has just been published on pypi.org if you want to give it a try.

**Comment by markaren** [comment]
Closing. Re-open if there is still an issue after updating to 0.4.0

**Comment by FlorianKarg** [comment]
it works now

**Comment by Arun-foxyy** [comment]
File "C:\Users\30051A\AppData\Local\Programs\Python\Python38-32\lib\site-packa
es\django\core\handlers\exception.py", line 47, in inner
   response = get_response(request)
 File "C:\Users\30051A\AppData\Local\Programs\Python\Python38-32\lib\site-packa
es\django\core\handlers\base.py", line 179, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
ypeError: __init__() takes 1 positional argument but 2 were given
24/Sep/2020 16:26:34] "GET /registerform/ HTTP/1.1" 500 57363

**Comment by markaren** [comment]
@Arun-foxyy , you should provide the PythonFMU version used and the constructor you are using to instantiate the Fmi2Slave super class..
